In [1]:
import numpy as np
import matplotlib.pyplot as plt

In [2]:
a = np.random.rand(4,2,5)
b = np.zeros([4,2,5])
# print(a,b)



In [3]:
print(a,b)

[[[0.65135596 0.54688022 0.0865981  0.13931837 0.09988283]
  [0.87661656 0.6958337  0.78691721 0.10154909 0.37824078]]

 [[0.25545651 0.32359407 0.41639337 0.490852   0.88799545]
  [0.75966338 0.04451233 0.73673304 0.00801322 0.37891553]]

 [[0.17488971 0.30622336 0.14014269 0.59643037 0.95100587]
  [0.59666174 0.021797   0.34595231 0.35204374 0.65882453]]

 [[0.38089465 0.83068134 0.69732081 0.08487297 0.50003781]
  [0.10881456 0.58218811 0.6859258  0.72071592 0.31416022]]] [[[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]]


In [4]:
%%time

XX,YY,ZZ = np.meshgrid(np.arange(a.shape[2]),np.arange(a.shape[1]),np.arange(a.shape[0]))

CPU times: user 174 µs, sys: 115 µs, total: 289 µs
Wall time: 197 µs


In [5]:
print(XX)

[[[0 0 0 0]
  [1 1 1 1]
  [2 2 2 2]
  [3 3 3 3]
  [4 4 4 4]]

 [[0 0 0 0]
  [1 1 1 1]
  [2 2 2 2]
  [3 3 3 3]
  [4 4 4 4]]]


In [6]:
from numba import jit

In [17]:
@jit(nopython=True)
def zip_3d(a,b,XX, YY, ZZ):
    output = np.zeros((*a.shape,2))
    for ai,bi,x,y,z in zip(a.ravel(),b.ravel(), XX.ravel(), YY.ravel(), ZZ.ravel()):
        output[x,y,z,0] = ai
        output[x,y,z,1] = bi
    # print(output)
    return output

In [8]:
@jit(nopython=True)
def zip_3d(a,b,XX, YY, ZZ):
    output = np.zeros((*a.shape,2))
    for i, a1 in enumerate(a):
        for j, a2 in enumerate(a1):
            for k, a3 in enumerate(a2):
                output[i,j,k] = [a3, b[i,j,k]]
    return output

In [9]:
XX,YY,ZZ = np.meshgrid(np.arange(a.shape[2]),
                               np.arange(a.shape[1]),
                               np.arange(a.shape[0])
                               )

In [10]:
%%time

zipped = zip_3d(a,b,XX,YY,ZZ )

CPU times: user 412 ms, sys: 30.1 ms, total: 442 ms
Wall time: 439 ms


In [11]:
print(zipped[0][0][0])
print(a[0][0][0], b[0][0][0])

[0.65135596 0.        ]
0.6513559583201944 0.0


In [12]:
print(zipped)

[[[[0.65135596 0.        ]
   [0.54688022 0.        ]
   [0.0865981  0.        ]
   [0.13931837 0.        ]
   [0.09988283 0.        ]]

  [[0.87661656 0.        ]
   [0.6958337  0.        ]
   [0.78691721 0.        ]
   [0.10154909 0.        ]
   [0.37824078 0.        ]]]


 [[[0.25545651 0.        ]
   [0.32359407 0.        ]
   [0.41639337 0.        ]
   [0.490852   0.        ]
   [0.88799545 0.        ]]

  [[0.75966338 0.        ]
   [0.04451233 0.        ]
   [0.73673304 0.        ]
   [0.00801322 0.        ]
   [0.37891553 0.        ]]]


 [[[0.17488971 0.        ]
   [0.30622336 0.        ]
   [0.14014269 0.        ]
   [0.59643037 0.        ]
   [0.95100587 0.        ]]

  [[0.59666174 0.        ]
   [0.021797   0.        ]
   [0.34595231 0.        ]
   [0.35204374 0.        ]
   [0.65882453 0.        ]]]


 [[[0.38089465 0.        ]
   [0.83068134 0.        ]
   [0.69732081 0.        ]
   [0.08487297 0.        ]
   [0.50003781 0.        ]]

  [[0.10881456 0.        ]
   [0.58

In [16]:
%%timeit

zipped = zip_3d(a, b,XX,YY,ZZ )

4.14 µs ± 330 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [19]:
%%timeit

zipped = zip_3d(a, b,XX,YY,ZZ )

1.74 µs ± 223 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [ ]:
print("hi")